[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/rest/v1/*"
  to = "https://sthucsfyzcpgaqmcwczy.supabase.co/rest/v1/:splat"
  status = 200
  force = true
  headers = {apikey = "sb_publishable_dP3E1mg0j-wlSwiUre7lyw_PhRiHzED", Authorization = "Bearer sb_publishable_dP3E1mg0j-wlSwiUre7lyw_PhRiHzED"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
