/*
  # Insertar datos de evaluación de trámites en la tabla observatory

  Inserta los 22 trámites evaluados con todos sus datos de digitalización,
  simplificación, interoperabilidad y otros indicadores.
*/

-- Insertar datos de los 22 trámites evaluados
INSERT INTO observatory (id, tramite, completamente_en_linea, adjunta_docs_digitalmente, firma_electronica_avanzada, resultado_electronico, num_pasos, num_requisitos, docs_misma_entidad, decl_jurada_innec, intercambia_datos, portal_interinst, usa_xroad_api, consulta_estado, notificacion_electronica, info_en_linea, atencion_alterna, multi_idioma, calif_usuarios, req_solo_por_ley, normativa_vigente, presuncion_buena_fe, maturity_level, evaluation_score) VALUES
(1, 'Registro de Nombre Comercial (RPI)', 50, 'Sí (portal acepta adjuntos)', 'Parcial (firma opcional)', 'Parcial (solicitud en línea, certificado físico)', 4, '1 formulario + pagos', 'No (no solicita docs propios)', 'No (no exige juramentos)', 'No (usuario aporta info)', 'No (portal RPI propio)', 'No (no indica uso)', 'Sí (eConsulta RPI)', 'Sí (notificación electrónica)', 'Sí (guías en web)', 'Sí (oficinas RPI)', 'No (solo español)', 'N/D (No hay datos)', 'Sí (requisitos ley PI)', 'Sí (Ley PI vigente)', 'Parcial (requiere copias legalizadas)', 2.8, 56),
(2, 'Inscripción al NIT (SAT)', 100, 'Sí (posible cargar DPI)', 'No (sin FEA)', 'Sí (NIT asignado en portal)', 3, '2 (DPI, email)', 'No (no pide docs SAT previos)', 'No (sin juramentos)', 'No (usuario provee datos)', 'No (portal SAT propio)', 'No (no se menciona)', 'N/A (asignación inmediata)', 'Sí (email confirmación)', 'Sí (SAT detalla en web)', 'Sí (agencias SAT físicas)', 'No (solo español)', 'N/D (No medido)', 'Sí (DPI según ley)', 'Sí (RTU digital vigente)', 'Sí (trámite simplificado)', 4.2, 84),
(3, 'Licencia Sanitaria (MAGA)', 0, 'No (se presenta físico)', 'No', 'No (licencia física)', 5, '5 docs (empresa)', 'No (no pide doc MAGA previo)', 'No', 'No (sin integración)', 'No (portal MAGA propio)', 'No', 'No (sin consulta web)', 'No (seguimiento manual)', 'Sí (detalles en catálogo)', 'Sí (oficinas MAGA)', 'No', 'N/D', 'Sí (basado en leyes)', 'Sí (reglamentos vigentes)', 'No (copias legalizadas requeridas)', 1.5, 30),
(4, 'Permiso Ambiental (MARN)', 50, 'Sí (SAGA adjunta EIA)', 'No (firma no integrada)', 'Parcial (resolución PDF)', 5, '~15 docs', 'Sí (pide licencias previas MARN)', 'No (sin juramentos extras)', 'Parcial (solicita opiniones)', 'Sí (VAC integra inst.)', 'No (plataforma propia)', 'Sí (seguimiento en SAGA)', 'Sí (alertas vía portal)', 'Sí (guías SAGA)', 'Parcial (ventanillas aún)', 'No', 'N/D', 'Sí (req. según ley ambiental)', 'Sí (RECSA reformado)', 'Parcial (acepta copias simples, pero trámites complejos)', 2.9, 58),
(5, 'Permiso Municipal Funcionamiento', 0, 'No (requiere gestión física)', 'No', 'No (licencia en papel)', 4, '~5 (DPI, patente, NIT, etc)', 'Sí (pide solvencia IUSI)', 'No', 'No (usuario lleva docs)', 'No (cada muni aparte)', 'No', 'No', 'No', 'Parcial (gral. info disponible)', 'Sí (oficinas municipales)', 'No', 'N/D', 'Sí (según ordenanzas locales)', 'Parcial (regs varían, actualizados)', 'No (pide docs ya emitidos por muni)', 1.3, 26),
(6, 'Registro de Marca (RPI)', 50, 'Sí (formularios en línea)', 'Parcial (firma opcional)', 'Parcial (certificado suele ser físico)', 4, '2 (solicitud, muestra marca)', 'No', 'No', 'No', 'No', 'No', 'Sí (eConsulta expedientes)', 'Sí (notif. electrónica)', 'Sí (portal RPI)', 'Sí (oficinas RPI)', 'No', 'N/D', 'Sí (Ley PI art. registro)', 'Sí (Ley PI vigente)', 'Parcial (procesos modernizándose)', 2.7, 54),
(7, 'Constitución de Empresa/Comerciante (Registro Mercantil)', 50, 'Sí (Sede Virtual permite PDF)', 'No (firma notarial física)', 'Parcial (patente descargable)', 5, '3 (Escritura, DPI, RTU)', 'No', 'No', 'No', 'No', 'No', 'Sí (estado en Sede Virtual)', 'Sí (email portal)', 'Sí (guías asisehace)', 'Sí (ventanilla física opcional)', 'No', 'N/D', 'Sí (Código Comercio)', 'Sí (Acuerdos actualizados)', 'Parcial (requiere entrega escritura)', 2.8, 56),
(8, 'Inscripción al RTU (SAT)', 100, 'Sí (adjunta escritura p/jurídicas)', 'No', 'Sí (NIT activo inmediato)', 3, '3-5 (depende tipo)', 'No', 'No', 'No', 'No', 'No', 'N/A (aprobación instantánea)', 'Sí (confirm. email)', 'Sí (guías SAT)', 'Sí (agencias SAT)', 'No', 'N/D', 'Sí (Código Tributario)', 'Sí (reglamento RTU digital)', 'Sí (simplificado en línea)', 4.1, 82),
(9, 'Licencia Municipal Funcionamiento', 0, 'No', 'No', 'No', 4, '~5 (DPI, patente, solvencias)', 'Sí (ej. solvencia IUSI)', 'No', 'No', 'No', 'No', 'No', 'No', 'Parcial (info general disponible)', 'Sí (oficinas muni)', 'No', 'N/D', 'Sí (según normativa muni)', 'Parcial (munis actualizan ordenanzas)', 'No (trámite burocrático tradicional)', 1.2, 24),
(10, 'Registro Patronal IGSS', 50, 'Sí (carga docs escaneados)', 'No', 'Parcial (número vía correo)', 3, '4 (DPI, escritura, RTU, form)', 'No', 'No', 'No', 'No', 'No', 'Parcial (consulta vía portal)', 'Sí (email confirmación)', 'Sí (PDF instructivo)', 'Sí (ventanillas IGSS)', 'No', 'N/D', 'Sí (Acuerdo JD IGSS)', 'Sí (reglamento vigente)', 'No (requiere copias legales)', 2.5, 50),
(11, 'Licencia de Construcción (Municipal)', 50, 'Sí (VAC permite planos digitales)', 'No (firmas planas físicas)', 'Parcial (resolución final en portal VAC)', 11, '≥10 (planos, título, dictámenes)', 'Sí (solvencia muni exigida)', 'No', 'Sí (VAC integra entes)', 'Sí (VAC opcional)', 'No (plataforma propia)', 'Sí (seguimiento en VAC)', 'Sí (alertas VAC)', 'Sí (portal VAC)', 'Parcial (canal físico previo)', 'No', 'N/D', 'Sí (Código construcción)', 'Sí (regl. actualizándose)', 'Parcial (ventanilla única agiliza)', 2.9, 58),
(12, 'Visado de Planos (Municipal)', 0, 'No', 'No', 'No', 5, '~3 (planos arq/estruc, título)', 'No (no docs muni previos)', 'No', 'No', 'No', 'No', 'No', 'No', 'Sí (requisitos publicados)', 'Sí (oficinas de planificación)', 'No', 'N/D', 'Sí (por código edilicio)', 'Parcial (normas locales vigentes)', 'No (proceso manual)', 1.4, 28),
(13, 'Solvencia IUSI (Municipal)', 0, 'No', 'No', 'No', 3, '2 (DPI, recibo pago)', 'N/A (es doc final)', 'No', 'No', 'No', 'No', 'N/A (se entrega al instante)', 'No (entrega física)', 'Parcial (info básica)', 'Sí (municipalidad)', 'No', 'N/D', 'Sí (req. por ordenanza)', 'Sí (normas vigentes)', 'No (usuario tramita certificado muni)', 1.3, 26),
(14, 'Registro de Exportador (VUPE)', 100, 'Sí (carga escrituras, etc)', 'No', 'Sí (código exportador vía web)', 5, '~3 (según tipo)', 'No', 'No', 'Sí (código a Aduanas SAT)', 'Sí (VUPE integra inst.)', 'No (sistema propio)', 'Sí (estado En revisión/Autorizado)', 'Sí (correo + llamada)', 'Sí (portal VUPE)', 'Parcial (asesoría presencial opcional)', 'No', 'N/D', 'Sí (base legal export)', 'Sí (normativa vigente)', 'Sí (trámite ágil en línea)', 4.0, 80),
(15, 'Declaración Aduanera (DUCA)', 100, 'Sí (adjunta docs según caso)', 'No', 'Sí (DUCA electrónica)', 3, '3 (factura, packing list, permisos)', 'No', 'No', 'Sí (info a aduana destino)', 'Sí (Sistema regional)', 'Parcial (SIECA integraciones)', 'Sí (tracking en sistema)', 'Sí (alertas Notifícame)', 'Sí (guías VUPE)', 'No (obligatorio online)', 'No', 'N/D', 'Sí (CAUCA/RECAUCA)', 'Sí (normativa 2019)', 'Sí (proceso unificado CA)', 4.3, 86),
(16, 'Certificado Fitosanitario (MAGA)', 50, 'Parcial (vía SEADEX/VUPE)', 'No', 'Parcial (e-Cert en sistema)', 6, '≤7 (form, insp., labs)', 'Sí (copia certif. MAGA)', 'No', 'Parcial (e-phyto intercambio)', 'Sí (SEADEX vía VUPE)', 'No', 'Sí (estados: En revisión, etc.)', 'Sí (notifica aprobación)', 'Sí (catálogo, MAGA anuncia)', 'Sí (ventanilla usuario MAGA)', 'No', 'N/D', 'Sí (según normas fitosanitarias)', 'Sí (IPPC eCert implementado)', 'No (tramite aún con pasos físicos)', 2.8, 56),
(17, 'Inscripción Patronal IGSS', 50, 'Sí (carga docs escaneados)', 'No', 'Parcial (número vía correo)', 3, '4 (DPI, escritura, RTU, form)', 'No', 'No', 'No', 'No', 'No', 'Parcial (consulta vía portal)', 'Sí (email confirmación)', 'Sí (PDF instructivo)', 'Sí (ventanillas IGSS)', 'No', 'N/D', 'Sí (Acuerdo JD IGSS)', 'Sí (reglamento vigente)', 'No (requiere copias legales)', 2.5, 50),
(18, 'Registro de Contratos (RECIT) (Mintrab)', 100, 'Sí (sube contrato escaneado)', 'No', 'Sí (constancia digital)', 6, '3 (nombramiento/RTU/contrato)', 'No', 'No', 'No', 'No', 'No', 'Sí (estatus en plataforma)', 'Sí (correo del sistema)', 'Sí (manuales y FAQ)', 'No (solo vía web)', 'No', 'N/D', 'Sí (art. 28-38 CT)', 'Sí (Acdo. 324-2019)', 'Sí (simplifica registro)', 4.0, 80),
(19, 'Libro de Salarios (Mintrab)', 100, 'N/A (carga solo RTU)', 'No', 'Sí (sello electrónico QR)', 8, '1 (RTU vigente)', 'No', 'No', 'Parcial (verif. RTU SAT)', 'No', 'No', 'Sí (estado en sistema)', 'Sí (notif. en sistema)', 'Sí (preguntas frecuentes)', 'No (solo en línea)', 'No', 'N/D', 'Sí (Art.102 CT)', 'Sí (Acdo. 124-2019)', 'Sí (elimina trámite físico)', 4.1, 82),
(20, 'Prueba Orientación Vocacional (USAC)', 50, 'N/A (form web sin adjuntos)', 'No', 'Parcial (cita impresa, resultado en portal)', 3, '0 (datos personales)', 'No', 'No', 'No', 'No', 'No', 'Sí (consulta asignación)', 'Sí (correo constancia)', 'Sí (pasos publicados)', 'No (proceso virtual obligatorio)', 'No', 'N/D', 'Sí (requisito académico)', 'Sí (normas USAC vigentes)', 'Sí (facilita asignación)', 3.2, 64),
(21, 'Pruebas Básicas de Admisión (USAC)', 50, 'N/A (registro en portal)', 'No', 'Parcial (resultado vía web)', 3, '0 (datos personales)', 'No', 'No', 'No', 'No', 'No', 'Sí (consulta notas en portal)', 'Sí (email convocatoria)', 'Sí (cronogramas en línea)', 'No (virtual obligatorio)', 'No', 'N/D', 'Sí (normas académicas)', 'Sí (reglamento admisión)', 'Sí (proceso centralizado)', 3.2, 64),
(22, 'Inscripción Académica (Universidad)', 50, 'Parcial (carga documentos escaneados)', 'No', 'Parcial (asignación carné por correo)', 4, '2 (Título bachiller, DPI)', 'No', 'No', 'No', 'No', 'No', 'Sí (estado de solicitud en portal)', 'Sí (correo de aceptación)', 'Sí (instructivos en web)', 'Parcial (soporte en campus)', 'No', 'N/D', 'Sí (requisitos legales: título)', 'Sí (normas actualizadas)', 'Parcial (acepta copias digitales temporales)', 2.9, 58)
ON CONFLICT (id) DO NOTHING;
