/*
  # Restauración - Paso 4: Insertar instituciones (45 registros del dump)
*/

INSERT INTO public.institutions (id, name, full_name, description, website, phone, email, address, working_hours, services, is_digital_enabled, social_media, contact_info, deleted_at, created_at, updated_at, category) VALUES
(1, 'Registro Mercantil', '', 'Registro Mercantil de Guatemala - Inscripción de empresas y comerciantes', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(2, 'SAT', '', 'Superintendencia de Administración Tributaria - Administración de impuestos', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(3, 'MSPAS', 'Ministerio de Salud Pública y Asistencia Social', 'Insitución encargada formular las políticas y hacer cumplir la salud preventiva y curativa y a las acciones de protección, promoción, recuperación y rehabilitación de la salud física y mental de los habitantes del país y a la preservación higiénica de medio ambiente', 'https://www.mspas.gob.gt/index.php/servicios', '2444 7474', '', '6ta. Av. 3-45 zona 11, Guatemala', '8:00 hrs a 17:00 hrs', 'Ejercer la rectoría del Sector Salud con la participación social, para proveer servicios de atención integral a la población, con equidad y calidad mediante el funcionamiento de redes integradas de salud en sus tres niveles, con el uso eficiente y transparente de los recursos, para garantizar el derecho a la salud.', true, 'https://www.facebook.com/MinisteriodeSaludPublicayAsistenciaSocial/', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:19:43.871983+00', NULL),
(4, 'MARN', 'Ministerio de Ambiente y Recursos Naturales', 'Institución encargada de proteger y fomentar los recursos, bienes y servicios naturales públicos. Tambien regula la gestion ambiental y el desarrollo sostenible.', 'http://www.marn.gob.gt', '24230500', 'rpublicas@marn.gob.gt', '7 avenida 03-67, zona 13, Ciudad Guatemala', '8:00 hrs a 16:30 hrs', 'Somos la institución que regula la gestión ambiental y promueve el desarrollo sostenible en Guatemala, de forma participativa.', true, 'https://www.facebook.com/marngtambiente/', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:18:49.702422+00', NULL),
(5, 'Municipalidad de Guatemala', '', 'Municipalidad de Guatemala - Permisos y licencias municipales', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(6, 'Registro de la Propiedad Intelectual', '', 'Registro de la Propiedad Intelectual - Protección de marcas y patentes', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(7, 'IGSS', '', 'Instituto Guatemalteco de Seguridad Social - Seguridad social y salud', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(8, 'Municipalidad', '', 'Municipalidades de Guatemala - Permisos y licencias locales', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(9, 'Colegio de Ingenieros / Arquitectos', '', 'Colegio de Ingenieros y Arquitectos - Visado de planos profesionales', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(10, 'MINECO / VUPE', '', 'Ministerio de Economía - Ventanilla Única para las Exportaciones', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(11, 'SAT / Aduanas', '', 'SAT Aduanas - Declaraciones aduaneras y exportaciones', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(12, 'MAGA', 'Ministerio de Agricultura, Ganadería y Alimentación', 'Institución encargada de fomentar el desarrollo rural del sector agropecuario, forestal e hidrobiológico, a traves de la transformación y modernización de los medios productivos, organizactivos y comerciales.', 'http://web.maga.gob.gt', '24137000', '', '7a. Avenida 12-90 zona 13, edificio Monja Blanca', '8:00 hrs a 16:30 hrs', 'Somos una Institución del Estado, que fomenta el desarrollo rural integral a través de la transformación y modernización del sector agropecuario, forestal e hidrobiológico, desarrollando capacidades productivas, organizativas y comerciales para lograr la seguridad y soberanía alimentaria y competitividad con normas y regulaciones claras para el manejo de productos en el mercado nacional e internacional, garantizando la sostenibilidad de los recursos naturales.', true, 'https://www.facebook.com/maga.gt', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:18:49.702422+00', NULL),
(13, 'MINTRAB', 'Ministerio de Trabajo y Previsión Social', 'Insitución que constituye la planificación, orientación, dirección y ejecución de la política laboral del país, con la colaboración de los distintos servicios y funcionarios de la rama administrativa de trabajo.', 'https://www.mintrabajo.gob.gt/', '24222501', '', '7 avenida 3-33 Zona 9 - Edificio Torre Empresarial', '9:00 hrs a 17:00 hrs', 'Ser un Ministerio Fortalecido, competente, moderno y confiable que promueva la cultura de respeto a la legislación laboral y el bienestar de la sociedad.', true, 'https://www.facebook.com/Mintrabajoguatemala/', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:19:43.871983+00', NULL),
(14, 'USAC', '', 'Universidad de San Carlos de Guatemala - Educación superior pública', '', '', '', '', '', '', false, '', '{}', NULL, '2025-10-22 03:12:23.842422+00', '2025-10-22 03:12:23.842422+00', NULL),
(17, 'MICIVI', 'Ministerio de Comunicaciones, Infraestructura y Vivienda', 'Institución encargada de direccionar, reglamentar y representar los sectores de comunicaciones, insfraestructura y vivienda. Al giaul que el mantenimiento y desarrollo del sistema de transporte.', 'http://www.civ.gob.gt', '2223 4000', '', '8a Avenida y 15 calle zona 13, Guatemala', '9:00 hrs a 17:00 hrs', 'Ser el ente rector que direcciona, reglamenta y representa en el ámbito nacional a los sectores de comunicaciones, infraestructura y vivienda; ejecutando políticas y estrategias para integrar al país con servicios acorde al desarrollo social y económico de la nación, contribuyendo a mejorar la competitividad a través del ejercicio de una administración y control eficientes.', true, 'https://www.facebook.com/civguate/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(18, 'MCD', 'Ministerio de Cultura y Deportes', 'Institución encargada a la conservación y desarrollo de la cultura guatemalteca, y el cuidado de la autenticidad de sus diversas manifestaciones; la protección de los monumentos y de los edificios, instituciones y áreas de interés histórico o cultural y el impulso de la recreación y del deporte no federado ni escolar.', 'https://mcd.gob.gt/', '22395000', 'info@mcd.gob.gt', '6 calle y 6 avenida zona 1 Palacio Nacional', '9:00 hrs a 17:00 hrs', 'Fortalecemos y promovemos la identidad guatemalteca y la cultura de paz, en el marco de la diversidad cultural y el fomento de la interculturalidad, mediante la protección, promoción y divulgación de los valores y manifestaciones culturales de los pueblos que conforman la nación guatemalteca, a través de una institucionalidad solida y mediante mecanismos de desconcentración, descentralización, transparencia y participación ciudadana, a efecto de contribuir a lograr un mejor nivel de vida para la población guatemalteca.', true, 'https://www.facebook.com/CulturayDeportesGT/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(19, 'MINDEF', 'Ministerio de la Defensa Nacional', 'Institución encargada de formular politicas para el cumplimiento de la defensa de la soberanía nacional. Actua como ógano intermediario entre el ejercito y las demas instituciones del estado.', 'http://www.mindef.mil.gt', '44974051', 'dideprensa@gmail.com', 'Ave. Reforma 1-45 zona 10.', '---', 'La Dirección General Administrativa del Ministerio de la Defensa Nacional, tiene como misión: planificar, coordinar, dirigir y controlar las actividades administrativas del Ministerio de la Defensa Nacional.', true, 'https://www.facebook.com/EjercitoGT/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(20, 'MIDES', 'Ministerio de Desarrollo Social', 'Institución encargada de generar políticas públicas para mejorar el nivel de vida de los grupos y personas vulnerables.', 'http://mides.gob.gt/webtwo/', '2300 5400', 'INFO@MIDES.GOB.GT', '5a. AV. 8-78 ZONA 9 GUATEMALA EDIFICIO PLAZA LAUDERDALE', '8:00 hrs a 16:30 hrs', 'El Ministerio de Desarrollo Social -Mides- es la entidad rectora que promueve y articula políticas y acciones para el desarrollo social sostenible de la población excluida de sus oportunidades básicas, con el fin de contribuir a mejorar sus condiciones de vida y reducir la pobreza.', true, 'https://www.facebook.com/Mides-Guatemala-1936605733288082/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(21, 'MINECO', 'Ministerio de Economía', 'Institución encargada de promover el desarrollo económico, creando empleos y oportunidades de inversión.', 'http://www.mineco.gob.gt/', '2412-0200', 'comunicacionsocial@mineco.gob.gt', '8a. Avenida 10-43 Zona 1 Ciudad de Guatemala', '8:00 hrs a 16:00 hrs', 'Ser la Dirección de apoyo al Viceministerio de Integración y Comercio Exterior en el diseño y negociación de acuerdos comerciales, así como en la promoción del adecuado desarrollo de la integración económica centroamericana y promover la expansión de la base exportable, para insertar a Guatemala en el contexto internacional y de la región centroamericana.', true, 'https://www.facebook.com/GUATEMINECO/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(22, 'MINEDUC', 'Ministerio de Educación', 'Institución encargada de generar oportunidades de enseñansa y aprendizaje.', 'http://www.mineduc.gob.gt/portal/index.asp', '24119595', 'info@mineduc.gob.gt', '6a. Calle 1-87 Zona 10', '9:00 hrs a 17:30 hrs', 'Somos una institución evolutiva, organizada, eficiente y eficaz, generadora de oportunidades de enseñanza-aprendizaje, orientada a resultados, que aprovecha diligentemente las oportunidades que el siglo XXI le brinda y comprometida con una Guatemala mejor.', true, 'https://www.facebook.com/MineducGuate/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(23, 'MEM', 'Ministerio de Energía y Minas', 'Institución encarga de regular los sectores de energía y minas, y fomentar el aprovechamiento adecuado de los recursos naturales', 'http://www.mem.gob.gt/', '2419 6464', '', 'Diagonal 17, 29-78 zona 11, Las Charcas', '8:00 hrs a 16:00 hrs', 'Propiciar y ejecutar las acciones que permitan la inversión destinada al aprovechamiento integral de los recursos naturales, que proveen bienes y servicios energéticos y mineros velando por los derechos de sus usuarios y de la sociedad en general.', true, 'https://www.facebook.com/MEMguatemala/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(24, 'MINFIN', 'Ministerio de Finanzas Públicas', 'Institución encarga de administrar los recursos financieros y patrimoniales del estado.', 'http://www.minfin.gob.gt/', '23743000', '', '8a. Avenida 20-59 Zona 1, Centro Cívico, Guatemala', '8:00 hrs a 16:30 hrs', 'Somos una institución que contribuye a la implementación de una política fiscal sostenible, mediante la gestión eficiente y transparente de los ingresos, los egresos y la deuda pública, para fortalecer el desarrollo social y el crecimiento económico nacional.', true, 'https://www.facebook.com/MinfinGT/', '{}', NULL, '2025-10-22 03:18:49.702422+00', '2025-10-22 03:18:49.702422+00', NULL),
(25, 'MINGOB', 'Ministerio de Gobernación', 'Institución encarga de generar polítcas relacionadas con el mantenimiento de la paz y orden público, al igual que la administración de los regímenes migratorios, penitenciares y los cuerpo de seguridad interna.', 'http://mingob.gob.gt/', '24138888', '', '6 avenida 13-71 zona 1, Guatemala, Guatemala', '9:00 hrs a 17:30 hrs', 'Institución rectora de las políticas relativas al mantenimiento de la paz, el orden público y la seguridad interior, que ejecuta las órdenes y resoluciones judiciales, administra los regímenes migratorio y penitenciario, conduce y regula los cuerpos de seguridad y cumple las funciones de gobernabilidad asignadas por la ley.', true, 'https://www.facebook.com/mingobguate/', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(26, 'MINEX', 'Ministerio de Relaciones Exteriores', 'Es el ente encargado de la formulación de las políticas y aplicación del régimen jurídico a las relaciones internacionales del Estado de Guatemala con otros Estados, siendo dependencia del Organismo Ejecutivo', 'https://www.minex.gob.gt/', '24100000', '', '2a Av. 4-17 zona 10, Ciudad de Guatemala', '8:00 hrs a 16:00 hrs', 'Es la institución del Estado a quien le corresponde bajo la dirección del Presidente de la República, la formulación de las políticas y la aplicación del régimen jurídico relativo a las relaciones del Estado de Guatemala con otros Estados y personas o instituciones jurídicas de derecho internacional, así como la representación diplomática del Estado, la nacionalidad guatemalteca y los asuntos diplomáticos y consulares.', true, 'https://www.facebook.com/minex.guatemala.9', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(29, 'SGP', 'Secretaría General de la Presidencia', 'Es el órgano responsable del apoyo jurídico y administrativo de carácter inmediato y constante del Presidente de la República.', 'https://sgp.gob.gt/', '23184600', 'libreacceso@sgp.gob.gt', '6av. 5-34 zona 1, Guatemala, Guatemala.', '9:00 hrs a 17:00 hrs', 'Somos un equipo de ciudadanos competentes y comprometidos, que brinda el apoyo Jurídico y Administrativo al Despacho de la Presidencia de la República de Guatemala.', true, 'https://www.facebook.com/SecretariaGeneralPresidenciaGuatemala/', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(30, 'SPP', 'Secretaría Privada de la Presidencia', 'Órgano que sirve de enlace en los asuntos que se dirijan al Presidente de la República de Guatemala, orientándolos conforme a su naturaleza, hacia distintas dependencias del Estado, cuya competencia les permite conocer los mismos.', 'http://www.secretariaprivada.gob.gt/index.html', '25026363', 'Informacion@secretariaprivada.gob.gt', '6ta avenida 4-46 zona 1', '9:00 hrs a 17:30 hrs', 'Somos la institución pública de apoyo directo a las funciones del Presidente Constitucional de la República, a través de la asistencia en asuntos privados y oficiales.', true, '', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(31, 'SCEP', 'Secretaría de Coordinación Ejecutiva de la Presidencia', 'Entidad pública comprometida con el desarrollo nacional, responsable de colaborar con el Presidente de la República en la coordinación, dirección y fortalecimiento del Sistema de Consejos de Desarrollo; y de la Descentralización del Organismo Ejecutivo.', 'https://www.scep.gob.gt/', '2210 4141', 'info@scep.gob.gt', '5ta. Avenida 6-06 Zona 1, Edificio IPM, 3er. y 4to. nivel Guatemala', '7:00 hrs a 15:30 hrs', 'Colaborar con el Presidente de la República de manera eficiente, eficaz y transparente en la coordinación del Sistema de Consejos de Desarrollo, la Descentralización del Organismo Ejecutivo y los mandatos Presidenciales.', true, 'https://www.facebook.com/secretariaejecutiva.scep', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(32, 'SCSPR', 'Secretaría de Comunicación Social de la Presidencia', 'Órgano que tiene la función de servir como vínculo de información con los medios de comunicación social, y de formular, coordinar y ejecutar la política de comunicación del Gobierno de la República.', 'https://www.scspr.gob.gt/', '2339 2501', '', '6 Avenida y 6 Calle - Palacio Nacional de la Cultura, Patio de la Paz, 1', '9:00 hrs a 17:30 hrs', '', true, 'https://www.facebook.com/scsprgt/', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(33, 'SIE', 'Secretaría de Inteligencia Estratégica del Estado', 'Institución responsable de producir inteligencia en los campos estratégicos, respetando el ámbito de competencia de las demás instituciones del Sistema Nacional de Inteligencia.', 'https://www.sie.gob.gt/portal/', '22227500', 'contactos@sie.gob.gt', '7a. Ave. 3-54, Zona 1 Ciudad de Guatemala', '8:00 hrs a 16:30 hrs', 'Somos la institución civil responsable de producir inteligencia estratégica, para identificar y prevenir riesgos, amenazas y vulnerabilidades que afecten la consecución de los objetivos nacionales.', true, 'https://www.facebook.com/sie.gob.gt/', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(34, 'SEGEPLAN', 'Secretaría de Planificación y Programación de la Presidencia', 'Ente de planificación del Estado, que asesora y asiste técnicamente a las instituciones públicas y al Sistema de Consejos de Desarrollo, para vincular los procesos de políticas públicas, planificación y programación con el Plan y la Política Nacional de Desarrollo.', 'https://www.segeplan.gob.gt/nportal/', '2504 4444', '', '9a. calle 10-44 zona 1, Guatemala, Guatemala.', '', '', true, 'https://www.facebook.com/SegeplanGT/', '{}', NULL, '2025-10-22 03:19:43.871983+00', '2025-10-22 03:19:43.871983+00', NULL),
(35, 'SAAS', 'Secretaría de Asuntos Administrativos y de Seguridad de la Presidencia de la República', 'Entidad permanente, con organización jerárquica y profesional, con especialidad en seguridad, y de naturaleza civil, cuyo régimen jurídico se determina su propia Ley Orgánica.', 'https://www.saas.gob.gt/', '23276000', 'reclutamiento@saas.gob.gt', '6 AV. "A" 4-18 ZONA 1 CALLEJÓN "DEL MANCHEN"', '--', 'Resguardar la legitimidad e institucionalidad democráticas del Estado de Guatemala, representadas por la Presidencia de la República.', true, '', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(36, 'SEPAZ', 'Secretaría de la Paz de la Presidencia de la República', 'Entidad desde su creación tiene como responsabilidad el apoyo, asesoría y coordinación para el cumplimiento de los compromisos gubernamentales de los Acuerdos de Paz de la Presidencia de la República.', 'https://sepaz.gob.gt/', '23224500', 'sepaz@sepaz.gob.gt', '17 Calle 8-36 zona 1, Ciudad de Guatemala', '8:30 hrs a 16:30 hrs', 'Somos la institución que coordina, asesora e incide en la formulación de políticas, planes y proyectos de la institucionalidad del Estado para el cumplimiento de los compromisos de los Acuerdos de Paz.', true, 'https://www.facebook.com/sepazgt', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(37, 'SBS', 'Secretaría de Bienestar Social de la Presidencia', 'Órgano administrativo que tiene a su cargo la formulación, coordinación y ejecución de las Políticas Públicas de Protección Integral de la Niñez y Adolescencia guatemalteca, contribuyendo al bienestar familiar y comunitario.', 'https://www.sbs.gob.gt/', '24143535', '', '32 calle 9-34 zona 11 las Charcas', '8:00 hrs a 16:30 hrs', 'Somos una institución especializada en la atención a la niñez y adolescencia vulnerada y amenazada en sus derechos, mediante programas y servicios de prevención, protección integral, reinserción y resocialización a nivel nacional con equidad e igualdad.', true, 'https://www.facebook.com/somossbs/', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(38, 'SEPREM', 'Secretaría Presidencial de la Mujer', 'Entidad asesora y coordinadora de políticas públicas para promover el desarrollo integral de las mujeres guatemaltecas y el fomento de una cultura democrática.', 'https://seprem.gob.gt/', '22079400', 'informacion@seprem.gob.gt', '4a. Calle 7-37 zona 1, Ciudad de Guatemala', '8:00 a 16:30 hrs', 'Institución gubernamental responsable de asesorar y coordinar acciones de política pública para institucionalizar en el Estado, la equidad entre hombres y mujeres.', true, 'https://www.facebook.com/SEPREM/', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(39, 'SAA', 'Secretaría de Asuntos Agrarios de la Presidencia de la República', 'Entidad que define y conduce estrategias que faciliten la resolución de conflictos derivados de la propiedad, posesión o tenencia de la tierra, por la vía del diálogo, negociación y arbitraje.', 'http://portal.saa.gob.gt/', '23121200', 'info@saa.gob.gt', 'Avenida La Reforma 8-50, Guatemala', '08:00 AM a 16:30 hrs', 'Somos la institución del Organismo Ejecutivo rectora del tema agrario. Con énfasis en la articulación de la política agraria, así como la resolución y transformación de conflictos relativos a la tierra.', true, 'https://www.facebook.com/SecretariaSAA/', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(40, 'SESAN', 'Secretaría de Seguridad Alimentaria y Nutricional', 'Órgano de coordinación del SINASAN, tiene la responsabilidad como dicho órgano, de concertar la operación interministerial del Plan Estratégico de Seguridad Alimentaria y Nutricional.', 'http://www.sesan.gob.gt/', '24111900', '', '8A Avenida 13-06, Zona 1', '8:00 a 16:30 hrs', 'Ser la institución responsable de la coordinación, integración y monitoreo de intervenciones de seguridad alimentaria y nutricional entre sector público, sociedad y organismos de cooperación internacional.', true, 'https://www.facebook.com/Sesangt/', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(41, 'SENACYT', 'Secretaría Nacional de Ciencia y Tecnología', 'Órgano que constituye el marco general para la orientación de las actividades científicas y tecnológicas en la República de Guatemala.', 'https://www.senacyt.gob.gt/portal/', '23172600', 'infosenacyt@senacyt.gob.gt', '3av. 13-28 Zona 1,', '8:00 a 16:30 hrs', '', true, 'https://www.facebook.com/senacyt/', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(42, 'SOSEP', 'Secretaría de Obras Sociales de la Esposa del Presidente de la República', 'Organismo encargado de impulsar e implementar programas de carácter social que beneficien a los niños, las niñas, las familias y la comunidad en general.', 'http://www.sosep.gob.gt/', '23276000', 'uip@sosep.gob.gt', '6TA. AVENIDA 4-65 ZONA 1, PUERTA NO. 1 CASA PRESIDENCIAL GUATEMALA', '8:00 a 16:30 hrs', 'Contribuir a desarrollo integral de las familias en condición de pobreza y pobreza extrema, especialmente del área rural.', true, 'https://www.facebook.com/sosepguatemala', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(43, 'SENABED', 'Secretaría Nacional de Administración de Bienes en Extinción', 'Entidad guatemalteca adscrita y dependiente de la Vicepresidencia de la República, la cual vela por la correcta administración de todos los bienes que tenga bajo su responsabilidad y los declarados en extinción del dominio.', 'https://www.senabed.gob.gt/', '24950600', '', 'Diagonal 6, 10-26 Zona 10', '8:00 a 16:30 hrs', 'Administrar los bienes de interés económico para el Estado, sujetos a la acción de extinción de dominio y los declarados en extinción de dominio por los órganos jurisdiccionales competentes.', true, 'https://www.facebook.com/senabedguatemala/', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL),
(44, 'SVET', 'Secretaría contra la Violencia sexual Explotación y Trata de Personas', 'Institución referente en la reducción de los delitos contra la violencia sexual, explotación y trata de personas. Ente rector, articulador y asesor en Guatemala para la prevención, atención, persecución y sanción de los delitos de violencia sexual, explotación y trata de personas.', 'http://www.svet.gob.gt/', '25048888', 'svet@vicepresidencia.gob.gt', '4a. Calle 5-51, zona 1', '8:00 a 16:30 hrs', 'Somos el ente rector, articulador y asesor en Guatemala para la prevención, atención persecución y sanación de los delitos de violencia sexual, explotación y trata de personas.', true, 'https://www.facebook.com/secretariasvet/', '{}', NULL, '2025-10-22 03:20:35.555422+00', '2025-10-22 03:20:35.555422+00', NULL)
ON CONFLICT (id) DO NOTHING;

-- Actualizar la secuencia al máximo id
SELECT setval('public.institutions_id_seq', COALESCE((SELECT MAX(id) FROM public.institutions), 1));
